Assignment/SE1616_Group5_Ass3/SE1616_Group5_Ass3/Models/Show.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SE1616_Group5_Ass3.Models
{
    public partial class Show
    {
        public Show()
        {
            Bookings = new HashSet<Booking>();
        }

        public int ShowId { get; set; }
        public int RoomId { get; set; }
        public int FilmId { get; set; }
        public DateTime? ShowDate { get; set; }
        [Range(0, 999.999)]
        
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? Price { get; set; }
        public bool? Status { get; set; }
        public int? Slot { get; set; }

        public virtual Film Film { get; set; }
        public virtual Room Room { get; set; }
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}

Assignment/SE1616_Group5_Ass3/SE1616_Group5_Ass3/Controllers/BookingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SE1616_Group5_Ass3.Models;

namespace SE1616_Group5_Ass3.Controllers
{
    public class BookingsController : Controller
    {
        private readonly CinemaContext _context;

        public BookingsController(CinemaContext context)
        {
            _context = context;
        }

        // GET: Bookings
        public async Task<IActionResult> Index(int? id)
        {
            var cinemaContext = _context.Bookings.Where(b => b.ShowId == id);
            HttpContext.Session.SetInt32("id", (int)id);
            List<Booking> list = await cinemaContext.ToListAsync();
            List<int> ints = new List<int>();
            foreach (Booking booking in list)
            {
                for(int i = 0; i < booking.SeatStatus.Length; i++)
                {
                    if (booking.SeatStatus[i].ToString().Equals("1"))
                    {
                        ints.Add(i);
                    }
                }
            }
            ViewBag.id = id;
            ViewBag.list = ints;
            return View(await cinemaContext.ToListAsync());
        }

        // GET: Bookings/Details/5
        // GET: Bookings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            Booking book = _context.Bookings.Find(id);
            ViewBag.Name = book.Name;
            ViewBag.Amount = book.Amount;
            List<int> list = new List<int>();
            ViewBag.SeatStatus = book.SeatStatus;
            return View(book);
        }

        // GET: Bookings/Create
        public async Task<IActionResult> Create()
        {
            int id = (int)HttpContext.Session.GetInt32("id");
            var cinemaContext = _context.Bookings.Where(b => b.ShowId == id);
            List<Booking> list = await cinemaContext.ToListAsync();
            List<int> ints = new List<int>();
            foreach (Booking booking in list)
            {
                for (int i = 0; i < booking.SeatStatus.Length; i++)
                {
                    if (booking.SeatStatus[i].ToString().Equals("1"))
                    {
                        ints.Add(i);
                    }
                }
            }
            ViewBag.id = id;
            ViewBag.list = ints;
            HttpContext.Session.SetInt32("Amount", 0);
            return View();
        }

        // POST: Bookings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BookingId,ShowId,Name,SeatStatus,Amount")] Booking booking, int? check)
        {
            int id = (int)HttpContext.Session.GetInt32("id");
            var cinemaContext = _context.Bookings.Where(b => b.ShowId == id);
            List<Booking> list = await cinemaContext.ToListAsync();
            List<int> ints = new List<int>();
            int Amount = (int)HttpContext.Session.GetInt32("Amount");
            HttpContext.Session.SetInt32("Amount", Amount+10);
            foreach (Booking book in list)
            {
                for (int i = 0; i < book.SeatStatus.Length; i++)
                {
                    if (book.SeatStatus[i].ToString().Equals("1"))
                    {
                        ints.Add(i);
                    }
                }
            }
            ViewBag.id = id;
            ViewBag.list = ints;
            if (ModelState.IsValid && check == 1)
            {
                _context.Add(booking);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ShowId"] = new SelectList(_context.Shows, "ShowId", "ShowId", booking.ShowId);
            return View(booking);
        }

        // GET: Bookings/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Booking book = _context.Bookings.Find(id);
            ViewBag.Name = book.Name;
            ViewBag.Amount = book.Amount;
            List<int> list = new List<int>();
            ViewBag.SeatStatus = book.SeatStatus;
            
            if (book == null)
            {
                return NotFound();
            }
            ViewData["ShowId"] = new SelectList(_context.Shows, "ShowId", "ShowId", book.ShowId);
            return View(book);
        }

        // POST: Bookings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BookingId,ShowId,Name,SeatStatus,Amount")] Booking booking)
        {
            if (id != booking.BookingId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(booking);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookingExists(booking.BookingId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ShowId"] = new SelectList(_context.Shows, "ShowId", "ShowId", booking.ShowId);
            return View(booking);
        }

        // GET: Bookings/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Booking book = _context.Bookings.Find(id);
            ViewBag.Name = book.Name;
            ViewBag.Amount = book.Amount;
            List<int> list = new List<int>();
            ViewBag.SeatStatus = book.SeatStatus;
            
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // POST: Bookings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var booking = await _context.Bookings.FindAsync(id);
            _context.Bookings.Remove(booking);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BookingExists(int id)
        {
            return _context.Bookings.Any(e => e.BookingId == id);
        }
    }
}

Assignment/SE1616_Group5_Ass3/SE1616_Group5_Ass3/Controllers/ShowsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SE1616_Group5_Ass3.Models;

namespace SE1616_Group5_Ass3.Controllers
{
    public class ShowsController : Controller
    {
        private readonly CinemaContext _context;

        public ShowsController(CinemaContext context)
        {
            _context = context;
        }

        // GET: Shows
        public async Task<IActionResult> Index()
        {
            var cinemaContext = _context.Shows.Include(s => s.Film).Include(s => s.Room);
            ViewData["shows"] = await cinemaContext.ToListAsync();
            ViewData["FilmId"] = new SelectList(_context.Films, "FilmId", "Title");
            ViewData["RoomId"] = new SelectList(_context.Rooms, "RoomId", "Name");
            HttpContext.Session.SetString("showDate", DateTime.Now.ToString());
            HttpContext.Session.SetInt32("roomId", 1);
            Show show = new Show();
            show.ShowDate = DateTime.Now;
            
            return View(show);
        }

        [HttpPost]
        public async Task<IActionResult> Index(Show show)
        {
            var cinemaContext = _context.Shows.Include(s => s.Film).Include(s => s.Room);
            ViewData["shows"] = await cinemaContext
                .Where(s => s.ShowDate == show.ShowDate
                && s.RoomId == show.RoomId
                && s.FilmId == show.FilmId)
                .ToListAsync();
            ViewData["FilmId"] = new SelectList(_context.Films, "FilmId", "Title", show.FilmId);
            ViewData["RoomId"] = new SelectList(_context.Rooms, "RoomId", "Name", show.RoomId);
            HttpContext.Session.SetString("showDate", show.ShowDate.ToString());
            HttpContext.Session.SetInt32("roomId", show.RoomId);
            return View(show);
        }

        // GET: Shows/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var show = await _context.Shows
                .Include(s => s.Film)
                .Include(s => s.Room)
                .FirstOrDefaultAsync(m => m.ShowId == id);
            if (show == null)
            {
                return NotFound();
            }

            return View(show);
        }

        // GET: Shows/Create
        public async Task<IActionResult> Create()
        {
            string date = HttpContext.Session.GetString("showDate");
            int id = (int)HttpContext.Session.GetInt32("roomId");
            ViewData["FilmId"] = new SelectList(_context.Films, "FilmId", "Title");
            ViewData["slot"] = await _context.Shows
                .Where(s => s.ShowDate == DateTime.Parse(date)
                && s.RoomId ==  id)
                .ToListAsync();
            Show show = new Show();
            show.ShowDate = DateTime.Parse(date);
            show.RoomId = id;
            return View(show);
        }

        // POST: Shows/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ShowId,RoomId,FilmId,ShowDate,Price,Status,Slot")] Show show)
        {
            if (ModelState.IsValid)
            {
                _context.Add(show);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["FilmId"] = new SelectList(_context.Films, "FilmId", "Title", show.FilmId);
            ViewData["RoomId"] = new SelectList(_context.Rooms, "RoomId", "Name", show.RoomId);
            
            return View(show);
        }

        // GET: Shows/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var show = await _context.Shows.FindAsync(id);
            if (show == null)
            {
                return NotFound();
            }

            ViewData["slot"] = await _context.Shows
                .Where(s => s.ShowDate == show.ShowDate
                && s.RoomId == show.RoomId
                && s.FilmId == show.FilmId
                && s.Slot != show.Slot).ToListAsync();

            ViewData["FilmId"] = new SelectList(_context.Films, "FilmId", "Title", show.FilmId);
            ViewData["RoomId"] = new SelectList(_context.Rooms, "RoomId", "Name", show.RoomId);

            return View(show);
        }

        // POST: Shows/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ShowId,RoomId,FilmId,ShowDate,Price,Status,Slot")] Show show)
        {
            if (id != show.ShowId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(show);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ShowExists(show.ShowId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["FilmId"] = new SelectList(_context.Films, "FilmId", "Title", show.FilmId);
            ViewData["RoomId"] = new SelectList(_context.Rooms, "RoomId", "Name", show.RoomId);
            return View(show);
        }

        // GET: Shows/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var show = await _context.Shows
                .Include(s => s.Film)
                .Include(s => s.Room)
                .FirstOrDefaultAsync(m => m.ShowId == id);
            if (show == null)
            {
                return NotFound();
            }

            return View(show);
        }

        // POST: Shows/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var show = await _context.Shows.FindAsync(id);
            _context.Shows.Remove(show);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ShowExists(int id)
        {
            return _context.Shows.Any(e => e.ShowId == id);
        }
    }
}

Assignment/SE1616_Group5_Ass3/SE1616_Group5_Ass3/Views/Shows/Create.cshtml
@model SE1616_Group5_Ass3.Models.Show

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Show</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ShowDate" />
            <input type="hidden" asp-for="RoomId" />
            <div class="form-group">
                <label asp-for="FilmId" class="control-label"></label>
                <select asp-for="FilmId" class="form-control" asp-items="ViewBag.FilmId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" onchange="" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Slot" class="control-label"></label>
                <select asp-for="Slot" class="form-control">
                    @for (var i = 1; i <= 9; i++)
                    {
                        var check = true;
                        @foreach (Show item in ViewBag.slot)
                        {
                            @if (@item.Slot == @i)
                            {
                                check = false;
                            }
                        }
                        @if (@check == true)
                       {
                           <option value="@i">@i</option>
                       }
                        
                    }

                </select>
                <span asp-validation-for="Slot" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

Assignment/SE1616_Group5_Ass3/SE1616_Group5_Ass3/Views/Shows/Delete.cshtml
@model SE1616_Group5_Ass3.Models.Show

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Show</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShowDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShowDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Slot)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Slot)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Film)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Film.CountryCode)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Room)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Room.RoomId)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ShowId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Assignment/SE1616_Group5_Ass3/SE1616_Group5_Ass3/Views/Shows/Details.cshtml
@model SE1616_Group5_Ass3.Models.Show

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Show</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShowDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShowDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Slot)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Slot)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Film)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Film.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Room)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Room.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ShowId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Assignment/SE1616_Group5_Ass3/SE1616_Group5_Ass3/Views/Shows/Edit.cshtml
@model SE1616_Group5_Ass3.Models.Show

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Show</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ShowId" />
            <input type="hidden" asp-for="ShowDate" />
            <input type="hidden" asp-for="RoomId" />
            <div class="form-group">
                <label asp-for="FilmId" class="control-label"></label>
                <select asp-for="FilmId" class="form-control" asp-items="ViewBag.FilmId"></select>
                <span asp-validation-for="FilmId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Slot" class="control-label"></label>
                <select asp-for="Slot" class="form-control">
                    @for (var i = 1; i <= 9; i++)
                    {
                        var check = true;
                        @foreach (Show item in ViewBag.slot)
                        {
                            @if (@item.Slot == @i)
                            {
                                check = false;
                            }
                        }
                        @if (@check == true)
                       {
                           <option value="@i">@i</option>
                       }
                        
                    }

                </select>
                <span asp-validation-for="Slot" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

Assignment/SE1616_Group5_Ass3/SE1616_Group5_Ass3/Views/Shows/Index.cshtml
@model SE1616_Group5_Ass3.Models.Show

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>
<form asp-action="Index">
    <div class="col-md-3">
    <div class="form-group">
    <label asp-for="RoomId"></label>
    <select asp-for="RoomId" asp-items="ViewBag.RoomId" class="form-control"></select>
    </div>
    <div class="form-group">
    <label asp-for="ShowDate" ></label>
    <input type="date" asp-for="ShowDate" class="form-control" />
    </div>
    <div class="form-group">
    <label asp-for="FilmId" ></label>
    <select asp-for="FilmId" asp-items="ViewBag.FilmId" class="form-control"></select>
    </div>
    <input type="submit" value="Search" class="btn btn-primary" />
    </div>
</form>
<br />

    <a asp-action="Create" >Create New</a>
   
@{
    int count = (ViewBag.shows as List<Show>).Count;
}

<p>The number of show : @count</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ShowDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Slot)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Film)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Room)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (Show item in ViewBag.Shows) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ShowDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Slot)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Film.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Room.Name)
            </td>
            <td>
                <a asp-controller="Bookings" asp-action="Index" asp-route-id="@item.ShowId">Bookings</a> | 
                <a asp-action="Edit" asp-route-id="@item.ShowId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ShowId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ShowId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>